name: flixage
description: Music streaming app
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # REST API
  dio: ^3.0.9
  http: ^0.12.0+4
  retrofit: ^1.3.1+1
  mime_type: ^0.3.0
  # Audio
  assets_audio_player: ^2.0.10
  # BLOC
  provider: ^4.0.4
  rxdart: ^0.24.1
  validators: ^2.0.0
  equatable: ^1.1.1
  # Animations
  animated_text_kit: ^2.2.0
  # Widgets
  settings_ui: ^0.4.0
  adaptive_dialog: ^0.8.0+1
  # Images
  cached_network_image: ^2.2.0+1
  image_picker: ^0.6.6+1
  # Cache manager WARNING: cache manager version must match cached_network_image
  flutter_cache_manager: ^1.2.0
  # Checking internet state
  connectivity: ^0.4.8+1
  # Security - Storing Token
  flutter_secure_storage: ^3.3.1+1
  # Utils
  meta: ^1.1.8
  json_annotation: ^3.0.0
  cupertino_icons: ^0.1.2
  logger: ^0.8.3
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.3
  mockito: ^4.1.1
  retrofit_generator: ^1.3.1+4
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
